/*
-EDITAR DATOS DE LA EMPRESA
-AÑADIR,EDITAR EMPLEADOS
-REGISTRO DE ENTRADA Y SALIDA EMPLEADOS
-CALCULO DE HORAS LABORADAS POR RANGO DE FECHAS
-PAGA POR HORAS
-CORREO DE LA EMPRESA PARA ENVIO DE EMAILS -> SI AÑADIMOS UN MODULO DE MENSAJERIA
*/